server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

spring:
  # 集群内配置刷新消息队列
  rabbitmq:
    host: 192.168.196.134
    port: 5672
    username: admin
    password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/olivia?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qiuhb
  # 分布式调用链服务端配置
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0 #采样比例0～1之间，1全部采样
    feign:
      enabled: true
    web:
      client:
        enabled: true
