server:
  port: 8021

spring:
  application:
    name: service-order
  # 集群内配置刷新消息队列
  rabbitmq:
    host: 192.168.196.134
    port: 5672
    username: admin
    password: 123456
  # 分布式调用链服务端配置
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0 #采样比例0～1之间，1全部采样
    feign:
      enabled: true
    web:
      client:
        enabled: true

# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka/
